# Generated by Django 2.0.6 on 2018-09-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
